-- Q1. What is the total revenue generated by male vs female customer?

SELECT 
    gender, SUM(purchase_amount) AS revenue_generated
FROM
    customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount also show avg(purchase_amount) in each row. 

select customer_id, purchase_amount, overall_avg 
from (select customer_id, purchase_amount, avg(purchase_amount) over() as overall_avg from customer where discount_applied = 'yes') t  where purchase_amount > overall_avg;

-- Q3. Which are the top 5  products with the highest avg review rating?

SELECT 
    item_purchased, avg_review_rating
FROM
    (SELECT 
        item_purchased,
            ROUND(AVG(review_rating), 2) AS avg_review_rating
    FROM
        customer
    GROUP BY item_purchased) c
ORDER BY avg_review_rating DESC
LIMIT 5;

-- Q4. Compare the avg purchase amounts between Standard and Express shippings?

SELECT 
    *
FROM
    customer
LIMIT 5;
SELECT 
    shipping_type, AVG(purchase_amount) AS avg_purchase_amount
FROM
    customer
GROUP BY shipping_type
HAVING shipping_type IN ('Express' , 'Standard');

 -- Q5. Do subscribed customers spends more? Compare avg spend and total revenue between subscribers and non-subscribers?
 
SELECT 
    subscription_status,
    round(AVG(purchase_amount), 2) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue,
    concat(round(sum(purchase_amount) * 100 / sum(sum(purchase_amount)) over(), 2),'%')  as pct_total_revenue
FROM
    customer
GROUP BY subscription_status;

-- Q6. which 5 products have the highest percenatage of purchases with discount applied?

SELECT 
    item_purchased,
    CONCAT(ROUND(100 * SUM(CASE
                        WHEN discount_applied = 'yes' THEN 1
                        ELSE 0
                    END) / COUNT(*),
                    2),
            '%') AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into new, returning, and Loyal based on their total number of previous purchases 
--     and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases, 
case 
when previous_purchases = 1 then 'NEW' 
when previous_purchases between 2 and 10 then 'RETURN' 
else 'LOYAL' end as customer_segment from customer) 
select customer_segment, count(*) as 'Number of customers' 
from customer_type 
group by customer_segment;

-- Q8. What are the top three most purchased products within each category?

with item_counts as (
select item_purchased, category, count(customer_id) as total_orders, 
row_number() over(partition by category order by count(customer_id) desc) as item_rank 
from customer group by item_purchased, category)
select item_rank, category, item_purchased, total_orders from item_counts where item_rank <= 3; 

-- Q9. Are customers who are repeat buyers (more than 5 previpus_purchases are also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(*) AS repeat_buyers,
    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER () AS pct_repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is revenue contribution of each age group?

SELECT age_group,
    SUM(purchase_amount) AS total_revenue,
    ROUND(
        SUM(purchase_amount) * 100.0 / 
        SUM(SUM(purchase_amount)) OVER (), 
    2) AS revenue_contribution_pct
FROM customer
GROUP BY age_group order by SUM(purchase_amount) desc;

